apiVersion: v1
kind: Service
metadata:
  name: otoorders
  labels:
    run: otoorders
spec:
  ports:
    # the port that this service should serve on
    - port: 8080 
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: otoorders
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: otoorders
    spec:
      containers:
      - name: otoorders
        image: thpr/otoorders:master
        ports:
        - containerPort: 8080
